import type { Metadata } from "next";
import { Playfair, Atkinson_Hyperlegible, IBM_Plex_Mono } from "next/font/google";
import '@/styles/global.scss'
import Header from "@/components/layout/header/Header";

const playfair = Playfair({
  variable: "--font-playfair",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800", "900"],
  
});

const atkinsonHyperlegible = Atkinson_Hyperlegible({
  variable: "--font-atkinsonHyperlegible",
  subsets: ["latin"],
  weight: ["400", "700", ],
});

const ibmPlexMono = IBM_Plex_Mono({
  variable: "--font-ibmPlexMono",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Workout Your Way",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${playfair.variable} ${atkinsonHyperlegible.variable} ${ibmPlexMono.variable}`}>
        <Header />
        {children}
      </body>
    </html>
  );
}
